language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo ldconfig 
  - make > /dev/null
script:
  - make
  - ./out/unitTests
apt: true
