language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo ldconfig 
  - make
script:
  - make test
  - make run-test
cache:  
  - apt
