language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo ldconfig 
  - make
script:
  - make test
  - make run-test
cache:  
  - apt
after_success:
  - make cov
  - coveralls-lcov --repo-token $COVERALLS_KEY scs-coverage.info
  - bash <(curl -s https://codecov.io/bash)
